### ISSUE TITLE
First contentful paint question/issue

### ISSUE THREAD

**Issue by MickeyKay** [paulirish/pwmetrics#113]
Re: the following run:
![image](https://cloud.githubusercontent.com/assets/3189678/25932156/05e03e2a-35ac-11e7-8222-7f59e3993a57.png)

Based on what I've read it seems like `First Contentful Paint` should always come before `Visually Complete 100%`, or is that incorrect? Either way, I'm curious what might lead to such disparate timings between these two metrics. Thanks!

**Comment by pedro93** [comment]
That is indeed an interesting run data. 
What version of pwmetrics and google chrome are you using?
As far as I know you correct that ```First Contentful Paint``` should appear before ```Visually Complete 100%```

Can you reproduce that sort of output consistently? Could you provide the url you used to test? 

Because pwmetrics is merely a wrapper on top of [lighthouse](https://github.com/GoogleChrome/lighthouse)'s performance functionality I would suggest you create an issue there to get your answer, they are much more knowledgeable than I am about the intrinsics of each metric.

cc @paulirish @samccone

**Comment by denar90** [comment]
Also will be nice to now which `pwmetrics` version you are using.

**Comment by MickeyKay** [comment]
Thanks for the reply. To answer your questions:
- Chrome: Version 58.0.3029.110 (64-bit)
- URL: testing a local dev URL, so not publicly available
- I cannot reproduce this in any obviously deterministic way

If I see this again I'll drop it over on the Lighthouse repo - thanks!
