### ISSUE TITLE
Consider wunderbar

### ISSUE THREAD

**Issue by paulirish** [paulirish/pwmetrics#157]
https://github.com/gribnoysup/wunderbar

![image](https://user-images.githubusercontent.com/39191/37236516-5d1d9cdc-23bd-11e8-9bfb-7bac5ae6e396.png)

might be nice instead of our barchart hax. but i'm not sure.

**Comment by denar90** [comment]
Looks pretty, I'll play with it. Should we consider migration after/during #158 ?

**Comment by denar90** [comment]
Looks interesting, not something we used to see:

![image](https://user-images.githubusercontent.com/6231516/37247576-dbaeb852-24c5-11e8-8d18-fdca88a55dc0.png)

Notes:
1. Just results of POC playground
2. Width of bars can be bigger
3. Colors are configurable

Open questions are:
- will it be better from UX perspective of view?
- In another hand, we should not think about supporting our fork of chart...

**Comment by gribnoysup** [comment]
This library almost made a full circle, haha 😸I made Wunderbar because I needed something flexible to print data from the PWMetrics and here you were evaluating the possibility to use it.

@paulirish first of all, thank you for even considering it, I'm stoked! 😍 Because of that I really want to try to convince you to use it once more. If you are still not feeling like it or just find this comment annoying, feel free to ignore it and sorry in advance!

- I noticed that you are supporting node >= 6 and Wunderbar was supporting node >= 8. This is not an issue anymore, I fixed it in a recent release 🎉 

- As @denar90 mentioned, one of the benefits of using Wunderbar is that you don't need to maintain `cli-chart` fork anymore. 

- The second improvement compared to current implementation is that Wunderbar uses [partial block symbols](https://github.com/gribnoysup/wunderbar/blob/master/wunder-bar-precise.png) to print charts, that means that even small differences in values will be visible on the chart. This wasn't documented well before 😅 

- @denar90 I noticed your concern about changing the UI, so I [experimented a little](https://github.com/gribnoysup/pwmetrics/blob/experiment/use-wunderbar/lib/chart/chart.ts) with replacing `cli-chart` with Wunderbar in my fork and here how it can look in comparison with the current chart. Instead of using default Wunderbar output, I am using building blocks from the library to keep the current PWMetrics UI, but with the slightly polished look.

![comparison](https://user-images.githubusercontent.com/5036933/37668236-433aac10-2c64-11e8-9226-2bd8d3922399.png)

I will also submit a PR that you can evaluate as a possible implementation. I'm open to feedback and will gladly change it in any way you want, even if some reasonable upstream changes in the library are needed. 

Again, if you still don't want to use the library, feel free to close that PR right away and thank you for considering Wunderbar 🙏

**Comment by denar90** [comment]
@gribnoysup thank you for so grounded and deep investigation! Looks really good! Do you think it will also be fine for windows users? We had some issues with chart behavior before...

**Comment by gribnoysup** [comment]
Good point! speaking only from a codebase perspective I would say it should work well, but I didn't have the chance to test on windows before 😅

Give me a few hours to bootstrap a VM; I'll check how it works and will report back!

**Comment by gribnoysup** [comment]
@denar90 I ran my experimental branch in Windows 10 cmd and PowerShell, and here is how it looks:

![virtualbox_windows 10 x64 _25_03_2018_20_21_12](https://user-images.githubusercontent.com/5036933/37878490-6e5e73a4-306a-11e8-95d2-d90a58e499f5.png)

It seems that only half box and full box symbols are supported by win systems out of the box; I'll fix this ASAP. Chart precision wouldn't be as good as on other platforms, but it will still be a step forward from the current version 👍 

I also noticed that checkmark for the successful run is not printed properly, instead, you can see `[?]` symbol. To avoid that you can also fall back to other symbols on win32 platforms, here is an example in the library called [`log-symbols`](https://github.com/sindresorhus/log-symbols/blob/master/index.js)

**Comment by denar90** [comment]
fixed in #161
