### ISSUE TITLE
relation with lighthouse ?

### ISSUE THREAD

**Issue by vikramvi** [paulirish/pwmetrics#160]
Can you please clarify how is this related to lighthouse, is it replacement / wrapper , why one should use this tool instead of just lighthouse ?

Thanks,
Vikram

**Comment by denar90** [comment]
Hi Vikram. 
PWMetrics is a tool/wrapper for Lighthouse. It runs Lighthouse using [chrome-launcher](https://github.com/GoogleChrome/chrome-launcher) -> gets metrics results due to [perf-config](https://github.com/paulirish/pwmetrics/blob/v3.1.6/lib/lh-config.ts) and either take a look at [docs](https://github.com/paulirish/pwmetrics/blob/v3.1.6/readme.md) or read [article](https://hackernoon.com/easy-progressive-web-metrics-9afa5ed857c2) we wrote to check all cool features we have.

**Comment by vikramvi** [comment]
Thanks @denar90 let me go through those and get back in case of further doubts.

Regards,
Vikram
