### ISSUE TITLE
Pwmetrics fails with pair number of runs

### ISSUE THREAD

**Issue by pedro93** [paulirish/pwmetrics#72]
When asking for an average of n runs (where n is a pair) the program will crash because of the calculations done in the [findMedianRun function](https://github.com/paulirish/pwmetrics/blob/master/lib/index.js#L204). 

Specifically what is happening is that the program can not find a TTI timing that is the exact median value of the runs, so it will return a ```undefined``` as the medianRun which generates the error seen in the screenshot below. By definition the median will average the middle 2 results.

If we merge https://github.com/paulirish/pwmetrics/pull/71 I also propose we change the way this function works to drop the TTI dependency which a user might not specify and which will crash the program.

![screen shot 2017-03-08 at 10 59 52](https://cloud.githubusercontent.com/assets/3718654/23701391/741cdda2-03ee-11e7-9f40-5edd9370ee0e.png)

**Comment by paulirish** [comment]
to pick median run we need to pick SOME metric to sort on. :)

I started with TTI because it's the most composite of the metrics... but rather than that we could just find whatever had the longest value of all metrics all runs. and then use whatever that metric is to sort by.
I'm nearly certain it will always be TTI, normally. but that would make this subsetting more reasonable.

hows that sound?

**Comment by pedro93** [comment]
Sounds good to me, with the desiredMetrics PR we may not always have tti metric so it would good to safeguard against it. 

Another question, what about when running pwmetrics with say 10 runs? 

There will not be a median value to pick from, as an average between the 5th and 6th (sorted) run will be choosen and that value has no match to the actual data retrieved.

**Comment by paulirish** [comment]
> Another question, what about when running pwmetrics with say 10 runs?

afaik, this case is already handled.

**Comment by pedro93** [comment]
Its not because of this line https://github.com/paulirish/pwmetrics/blob/master/lib/index.js#L205

Ignore the unexpected console.logs.

![screen shot 2017-03-10 at 17 42 45](https://cloud.githubusercontent.com/assets/3718654/23806286/05de9854-05b9-11e7-9293-fa90b7c02746.png)

**Comment by pedro93** [comment]
@paulirish Any particular way you to want to handle finding the largest metric to sort by? I was thinking we could use the [metricsIds](https://github.com/paulirish/pwmetrics/blob/master/lib/metrics.js#L7) as a sorted (by biggest value) collection. 
We could also try some sort of dynamic calculation, not sure how to that atm though. 

In relation to even number of runs, we could detect that in the findMedianRun via the ```(results.length % 2 === 0)``` and if so we select the immediately succeeding value (so, we would show the slightly worse values)?

**Comment by paulirish** [comment]
sorry. i wrote a reply somewhere but i guess it was lost. :/

Here's roughly what i'm thinking...

1. for each runResult..
1. get the maximum timing value
1. `const maxWithinRun = Math.max(...result.timings.map(r => r.timing))`
1. see what the max is of all of those across all runs
1. then use the `timing.id` of whatever timing had that maxAcrossRuns
1. then basically do the rest of what `findMedianRun` does now, but with this `timing.id` instead of TTI.

It's very likely there's a better approach than that, but that's my current take.

**Comment by pedro93** [comment]
I came across something interesting that may invalidate this approach. The visually complete 85% metric has the same timing value as TTI. As of yet the 

I don't know exactly how these two audits work but is this the expected behaviour?

![screen shot 2017-03-13 at 09 41 02](https://cloud.githubusercontent.com/assets/3718654/23848920/3345b182-07d1-11e7-944b-c8a307aef50b.png)

**Comment by denar90** [comment]
@pedro93 as far as `vc85` one of the indicators for `tti`, I suppose it can happens.

**Comment by pedro93** [comment]
TIL. I also noticed that ```vc100``` is greater than ```tti``` from what I've seen so far.

**Comment by paulirish** [comment]
Yeah there's no guarantee on what is first/last between vc100 and tti. Either could be the last thing.

It's also possible for FMP, vc85, vc100 and TTI to all happen at (roughly) the same time. But that'd be atypical. :)
